import { serve } from "https://deno.land/std@0.224.0/http/server.ts";

interface RequestPayload {
  userImage: string;
  dhotiImage: string;
  bodyType: "full" | "half";
}

const GEMINI_MODEL = "gemini-2.5-flash-image";
const GEMINI_API_URL = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`;

serve(async (req: Request) => {
  const origin = req.headers.get("Origin") || "*";
  const corsHeaders: Record<string, string> = {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
    "Vary": "Origin",
  };

  if (req.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: corsHeaders });
  }

  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), {
      status: 405,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  }

  const geminiApiKey = Deno.env.get("GEMINI_API_KEY")?.trim();

  if (!geminiApiKey) {
    return new Response(JSON.stringify({ error: "Gemini API key not configured" }), {
      status: 500,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  }

  try {
    const payload = (await req.json()) as RequestPayload;
    const { userImage, dhotiImage, bodyType } = payload;

    if (!userImage || !dhotiImage) {
      return new Response(JSON.stringify({ error: "Missing required images" }), {
        status: 400,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }

    const promptText = `Edit the provided photograph.

Strict rules:
- Do not change the face, hairstyle, skin tone, pose, or background.
- Do not change the upper body clothing.
- Only modify the lower body.

Task:
- Dress the person in the provided dhoti image.
- If the full body is visible (bodyType: ${bodyType}), replace only the lower body clothing with the dhoti.
- If the image shows only half body (bodyType: ${bodyType}), naturally generate the missing lower body and dress it with the dhoti.

Style:
- Ultra-realistic photographic quality
- Natural fabric folds and drape
- Correct body proportions and perspective
- Preserve original lighting and shadows
- The dhoti must look naturally worn, not artificial.

Output:
- High-resolution realistic photo
- No distortion
- No extra body parts
- No background changes

Avoid: cartoon, illustration, mannequin, doll, fake, unrealistic, extra legs, extra arms, altered face, altered background, blur, low quality`;

    const geminiPayload = {
      contents: [
        {
          parts: [
            { text: promptText },
            {
              inline_data: {
                mime_type: "image/jpeg",
                data: userImage,
              },
            },
            {
              inline_data: {
                mime_type: "image/jpeg",
                data: dhotiImage,
              },
            },
          ],
        },
      ],
      generationConfig: {
        response_modalities: ["IMAGE"],
      },
    };

    const response = await fetch(`${GEMINI_API_URL}?key=${geminiApiKey}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(geminiPayload),
    });

    if (!response.ok) {
      const errorData = await response.json();
      console.error("Gemini API error:", response.status, errorData);
      
      // Handle quota/billing errors
      if (response.status === 429 || response.status === 402 || (errorData.error?.message?.includes("quota") || errorData.error?.message?.includes("credit"))) {
        return new Response(JSON.stringify({ 
          error: "AI preview is temporarily unavailable. Please try again later." 
        }), {
          status: 500,
          headers: { "Content-Type": "application/json", ...corsHeaders },
        });
      }

      return new Response(JSON.stringify({ error: "Failed to generate image" }), {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }

    const data = await response.json();
    const candidate = data.candidates?.[0];
    const imagePart = candidate?.content?.parts?.find((part: any) => part.inline_data);

    if (imagePart?.inline_data?.data) {
      return new Response(JSON.stringify({ image: imagePart.inline_data.data }), {
        status: 200,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }

    return new Response(JSON.stringify({ error: "No image generated by the AI" }), {
      status: 500,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  } catch (e) {
    const msg = e instanceof Error ? e.message : "Unexpected error";
    console.error("AI Try-On error:", msg);
    return new Response(JSON.stringify({ error: msg }), {
      status: 500,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  }
});
